List<Map<String, dynamic>> countriesData = [
  {"name": "Japan", "count": 32},
  {"name": "Solar System", "count": 14},
  {"name": "Iraq", "count": 13},
  {"name": "United States", "count": 12},
  {"name": "France", "count": 9},
  {"name": "Croatia", "count": 8},
  {"name": "Pakistan", "count": 6},
  {"name": "Cuba", "count": 6},
  {"name": "Australia", "count": 6},
  {"name": "United Kingdom", "count": 6},
  {"name": "Canada", "count": 5},
  {"name": "Russia", "count": 5},
  {"name": "South Africa", "count": 4},
  {"name": "Germany", "count": 3},
  {"name": "Italy", "count": 3},
  {"name": "Mexico", "count": 3},
  {"name": "Austria", "count": 2},
  {"name": "Turkey", "count": 2},
  {"name": "Panama", "count": 2},
  {"name": "Egypt", "count": 2},
  {"name": "China", "count": 2},
  {"name": "East Timor", "count": 2},
  {"name": "Antarctica", "count": 2},
  {"name": "India", "count": 2},
  {"name": "Sweden", "count": 2},
  {"name": "Estonia", "count": 1},
  {"name": "Djibouti", "count": 1},
  {"name": "Senegal", "count": 1},
  {"name": "Kazakhstan", "count": 1},
  {"name": "Denmark", "count": 1},
  {"name": "Bosnia and Herzegovina", "count": 1},
  {"name": "Benin", "count": 1},
  {"name": "Cabo Verde", "count": 1},
  {"name": "Cyprus", "count": 1},
  {"name": "Nigeria", "count": 1},
  {"name": "Switzerland", "count": 1},
  {"name": "Ecuador", "count": 1},
  {"name": "Tajikistan", "count": 1},
  {"name": "Comoros", "count": 1},
  {"name": "Belize", "count": 1},
  {"name": "Norway", "count": 1},
  {"name": "Botswana", "count": 1},
  {"name": "Armenia", "count": 1},
  {"name": "Belarus", "count": 1},
  {"name": "Central African", "count": 1},
  {"name": "Brazil", "count": 1},
  {"name": "Universe", "count": 1},
  {"name": "Dominica", "count": 1},
  {"name": "Jaoan", "count": 1},
  {"name": "Bolivia", "count": 1},
  {"name": "Angola", "count": 1},
  {"name": "Indian Ocean", "count": 1},
  {"name": "Bahrain", "count": 1},
  {"name": "Vatican City", "count": 1},
  {"name": "Congo, Republic of the", "count": 1},
  {"name": "Bulgaria", "count": 1},
  {"name": "Congo, DR", "count": 1},
  {"name": "Belgium", "count": 1},
  {"name": "Burundi", "count": 1},
  {"name": "Nepal", "count": 1},
  {"name": "Costa Rica", "count": 1},
  {"name": "Bhutan", "count": 1},
  {"name": "Milky Way", "count": 1},
  {"name": "Haiti", "count": 1},
  {"name": "Equatorial Guinea", "count": 1},
  {"name": "Antigua and Barbuda", "count": 1},
  {"name": "Burkina Faso", "count": 1},
  {"name": "Andorra", "count": 1},
  {"name": "El Salvador", "count": 1},
  {"name": "Bangladesh", "count": 1},
  {"name": "Cameroon", "count": 1},
  {"name": "Czech Republic", "count": 1},
  {"name": "North Pacific Ocean", "count": 1},
  {"name": "Dominican Republic", "count": 1},
  {"name": "Cambodia", "count": 1},
  {"name": "Ireland", "count": 1},
  {"name": "Eritrea", "count": 1},
  {"name": "Brunei", "count": 1},
  {"name": "South Korea", "count": 1},
  {"name": "Barbados", "count": 1},
  {"name": "North Atlantic Ocean", "count": 1},
  {"name": "Albania", "count": 1},
  {"name": "Saudi Arabia", "count": 1},
  {"name": "Argentina", "count": 1},
  {"name": "Cook Islands", "count": 1},
  {"name": "Azerbaijan", "count": 1},
  {"name": "Greece", "count": 1},
  {"name": "Bahamas", "count": 1},
  {"name": "Afghanistan", "count": 1},
  {"name": "Chad", "count": 1},
  {"name": "Algeria", "count": 1},
  {"name": "Gambia", "count": 1}
];


List<Map<String, dynamic>> periodData = [
{"name": "Common-Era", "count": 167},
{"name": "Million Years", "count": 23},
{"name": "Before-CommonEra", "count": 17},
{"name": "Thousand Years", "count": 3},
];
