#!/bin/sh

# Makes sure we break the script on any error.
set -e

# Build the web app.
cd acorn_flutter
flutter build web --release --web-renderer canvaskit
cd ..

# Copy the build files into the web/app diretory.
rm -rf acorn_server/web/app
cp -r acorn_flutter/build/web acorn_server/web/app

# Move the index.html file into the templates directory.
mkdir -p acorn_server/web/templates
mv acorn_server/web/app/index.html acorn_server/web/templates/index.html