#!/bin/sh

# タイムスタンプを生成
BUILD_ID=$(date +"%Y%m%d")

# Dart を上書き
cat <<EOF > ../acorn_flutter/lib/utils/build_id.dart
class BuildId {
  static const String value = '$BUILD_ID';
}
EOF

echo "Build ID generated: $BUILD_ID"

# Makes sure we break the script on any error.
set -e

# Build the web app
cd ../acorn_flutter
flutter build web --release --no-tree-shake-icons
cd ..

# Copy the build files into the web/app diretory.
rm -rf acorn_server/web/app
cp -r acorn_flutter/build/web acorn_server/web/app

# Move the index.html file into the templates directory.
mkdir -p acorn_server/web/templates
mv acorn_server/web/app/index.html acorn_server/web/templates/index.html